connect 'jdbc:derby://127.0.0.1:1527/db_sigep;user=usr_sigep;password=123';
call syscs_util.syscs_export_query('SELECT distinct DBO.NEP_ETIQUETA.ETQ_TX_ETIQUETA FROM DBO.NEP_PLP INNER JOIN DBO.NEP_OBJETO_POSTAL ON DBO.NEP_OBJETO_POSTAL.PLP_CO_PLP = DBO.NEP_PLP.PLP_CO_PLP INNER JOIN DBO.NEP_ETIQUETA ON DBO.NEP_ETIQUETA.OBJ_CO_OBJETO_POSTAL = DBO.NEP_OBJETO_POSTAL.OBJ_CO_OBJETO_POSTAL WHERE DBO.NEP_PLP.PLP_DT_POSTAGEM >= ''2019-01-01''','./objetos.csv', ';', null, null);
exit;
